---
name: Java CI with Maven
on:
  push:
    branches:
      - main
jobs:
  Compile:
    runs-on: runner-1
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Download Maven dependencies
        run: mvn dependency:go-offline -B
      - name: Build with Maven
        run: mvn compile
      
  Security-checks:
    runs-on: runner-1
    needs: Compile
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Trivy FS scan
        run: |
             sudo apt-get install wget gnupg -y
             wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
             echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
             sudo apt-get update -y
             sudo apt-get install trivy -y
      - name: Trivy scan
        run: trivy fs --format table -o fs-report.json .

      - name: gitleaks Installation
        run: sudo apt install gitleaks -y

      - name: gitleaks scan
        run: gitleaks detect source . -r gitleaks-report.json -f json
  Testing:
    runs-on: runner-1
    needs: Security-checks
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Testing
        run: mvn test
  Build-project-sonar-scan:
    runs-on: runner-1
    needs: Testing
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Build Project
        run: mvn package
      - name: uploading artifact
        uses: actions/upload-artifact@v7
        with:
         name: app-jar
         path: target/*.jar
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.1 # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  docker-build-push:
    runs-on: runner-1
    needs: Build-project-sonar-scan
    steps:
      - uses: actions/checkout@v4
      - name: Downloading the artifact
        uses: actions/download-artifact@v8
        with:
          name: app-jar
          path: app
          
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: user/app:latest








             
